### ISSUE TITLE
Load balancer health check redirected; not making it to the app

### ISSUE THREAD

**Issue by gsisson** [tobmatth/rack-ssl-enforcer#102]
Hi.  Apologies if this is the wrong location for this question.

We are trying to use your gem to create a single exception for a single endpoint in our use of SSL in our app.   We want to allow a port 80 health check inquiry from a load balancer (LB) but we can't seem to configure your gem (or maybe nginx?) correctly to accomplish this.   Rails (nginx?) keeps redirecting the LB's health request with a 301 regardless of our rack-ssl-enforcer configuration.

Before attempting to use your gem, we had our app working fine in the Elastic BeanStalk environment of AWS, with an LB configured to handle SSL termination (and with the default TCP LB healthcheck).   We configured the app for SSL with the "config.force_ssl = true" setting so that the app only had to deal with port 80 traffic, and we didn't modify the default nginx configuration at all.   With this setup, Rails works fine and accepts only port 80 traffic with a special header HTTP_X_FORWARDED_PROTO indicating that the LB has terminated the 443 traffic and routed it on to the app on port 80.   And this works fine for us.

But now, we desire the LB to do a health check on our HTTP /alive endpoint.   But we found that this didn't work, since the health check from the LB (sent on port 80) comes in WITH OUT that special header the LB usually adds to requests from a browser.   Rails sees no head so it does a 301 redirect to HPPTS.  The LB then considers the health check to have failed. :-(

To fix this, we had hoped to use your gem to configure our app to allow our /alive endpoint to be hit without the HTTP_X_FORWARDED_PROTO header.  So, we removed the Rails "config.force_ssl = true" line, and added these two lines of configuration for your gem:

- config.middleware.use Rack::SslEnforcer, ignore: lambda { |request| request.env["HTTP_X_FORWARDED_PROTO"].blank? }, strict: true
- config.middleware.insert_before  ActionDispatch::Cookies, Rack::SslEnforcer

We expected that this would simply allow non-SSL traffic to hit our /alive endpoint.  But instead, we always see a 301 redirect for the LB health check, and never see the lambda code get called.   We tried applying some of the nginx config settings your README suggests, but did not find them to accomplish anything.

If you could offer us any advice, that would sure be appreciated.   Thank you very much!

**Comment by tobmatth** [comment]
Hi,

could you post relevant sections of your nginx configuration?

**Comment by gsisson** [comment]
Hi Tobias, thank you for your reply.  I appreciate your help!

I don't trust that I know the "relevant" sections of the nginx config, so I'll send you the full config as shown by "nginx -T".   I will attempt to attach a text file showing a terminal session with that information, as well as showing you the uname of the OS, the directory I was working in, and the specific nginx config override file we placed on the system and where we placed it.

Also, note that the only nginx file we added was the one "webapp_load_balance_health_check.conf" file.

Thank you again Tobias,
-- Glenn

[nginx-T.txt](https://github.com/tobmatth/rack-ssl-enforcer/files/1682485/nginx-T.txt)

**Comment by tobmatth** [comment]
Hi Glenn,

if i understand correctly, you want your setup to behave like this:

    1. Client ---> http://your.domain.tld ---> LB ---> NginX ---> Rails # redirect to HTTPS
    2. Client ---> https://your.domain.tld ---> LB ------> NginX ---> Rails # serve app
    3. LB ---> http://your.domain.tld/alive ---> NginX ---> Rails # serve app

1. LB has set HTTP_X_FORWARDED_PROTO to http
2. LB has set HTTP_X_FORWARDED_PROTO to https
3. LB has initiated the request, HTTP_X_FORWARDED_PROTO not set

For your scenario, `config.middleware.insert_before ActionDispatch::Cookies, Rack::SslEnforcer, except: %r{^/alive/}` should do the trick. HTH, if it does not, please post the output of `rake middleware`

**Comment by gsisson** [comment]
Yes, Tobias, you understand what we were trying to set up.   And your suggested code did the trick!  Thanks!  Just had to change your regex to %r{^/alive$} (since we are hitting "/alive" not "/alive/").  I also removed the nginx configuration we were trying to use earlier... they weren't needed after all.

Again, thank you very much for your help Tobias, and thanks for a great gem that has really helped us out!

**Comment by tobmatth** [comment]
Glad you figured it out. I'm closing here, take care!
