### ISSUE TITLE
Does rack-ssl-enforcer have support for ssl client verification?

### ISSUE THREAD

**Issue by watta90** [tobmatth/rack-ssl-enforcer#104]
I need to verify a client with an SSL certificate, is that possible to enable with this gem? I don't need it for the whole site but only for some paths. 

Thanks in advance!

**Comment by tobmatth** [comment]
Hi,

SSL client certificate verification is not supported. Rack-SSL-Enforcer is about enforcing secure / non-secure connections based on certain constraints, so i'm afraid this is out of scope of this gem.
You propably want to take a look at [rack-client-certs](https://github.com/dkam/rack-client-certs) or [rails-auth](https://github.com/square/rails-auth)

HTH
Tobi
