### ISSUE TITLE
:strict option + AJAX requests

### ISSUE THREAD

**Issue by blelump** [tobmatth/rack-ssl-enforcer#36]
Hi,

that shouldnt be actually an issue, rather an improvement. I've tried to deal with AJAX requests and both, ssl as  well as non-ssl requests combined with :strict option. That of course leads my AJAX request to redirection, depending on additional options specified (:only or :except). So, for instance, if I'll add a rule to :only array that matches my ajax request url, it will work if current page is served via https and will fail via http.

Next thing I did, I tried to implement additional :skip option (an array of rules; if any rule matches, then such request won't be processed at all and just skipped) which would help in these cases, while dealing with ajax requests on both ssl and non-ssl pages using :strict option. However, my current problem is that such :skip option does not apply to current implementation at all or I dont know how to deal with it. Perhaps it is completely wrong approach and it might be solved much easier and I just don't know how... Do you have an idea how to deal with it, I mean using :strict with ssl and plain requests?

**Comment by tobmatth** [comment]
I'm closing here. Feel free to reopen...
