### ISSUE TITLE
Cookie session state shared across http and https without disabling force_secure_cookies

### ISSUE THREAD

**Issue by kbaum** [tobmatth/rack-ssl-enforcer#58]
Due to issues out of our control right now, I have some logged in pages that are https and some that are http.  After reading through the github readme, it would seem that i would have to disable force_secure_cookies for this to function properly.

https://github.com/tobmatth/rack-ssl-enforcer#secure-cookies-disabling

That being said I am able to jump between logged in http and https pages without being logged out.  My configuration looks like:

```ruby
config.middleware.use Rack::SslEnforcer, only: ['/users/sign_in', %r{/users/password/*}, %r{^/user_profile.*}], ignore: [%r{^/assets}], strict: true 
```

Am I misinterpreting the readme?

thx!

**Comment by tobmatth** [comment]
@kbaum I'm closing here. Please reopen if needed.
