### ISSUE TITLE
How to handle URI::InvalidURIError?

### ISSUE THREAD

**Issue by PikachuEXE** [tobmatth/rack-ssl-enforcer#78]
Caused by any bad URL like `http://example.com/<lan`

stacktrace:
```
/usr/lib/ruby/2.1.0/uri/common.rb:176→ split
/usr/lib/ruby/2.1.0/uri/common.rb:712→ split
rack-ssl-enforcer-0.2.8/lib/rack/ssl-enforcer.rb:156→ replace_scheme
rack-ssl-enforcer-0.2.8/lib/rack/ssl-enforcer.rb:92→ modify_location_and_redirect
rack-ssl-enforcer-0.2.8/lib/rack/ssl-enforcer.rb:50→ call
```

**Comment by henrywho** [comment]
:+1:

**Comment by henrywho** [comment]
:+1: 

I was running into this issue with urls that have curly braces, like http://example.com/?{}

**Comment by fzagarzazu** [comment]
Monkey patching example:
    module Rack
      class SslEnforcer
        alias_method :modify_location_and_redirect_orig, :modify_location_and_redirect
        def modify_location_and_redirect
          modify_location_and_redirect_orig
        rescue URI::InvalidURIError
          body = { status: 400, error: 'Bad Request' }
          [400, { 'Content-Type' => 'application/json' }, [ body.to_json ] ]
        end
      end
    end

**Comment by PikachuEXE** [comment]
@fzagarzazu Thanks for your solution!
I implement it to return HTML instead, aligning with the existing behaviour. 
See https://github.com/tobmatth/rack-ssl-enforcer/blob/master/lib/rack/ssl-enforcer.rb#L97

**Comment by PikachuEXE** [comment]
Can a new version be released?
Last version is released > 6 months ago

**Comment by tobmatth** [comment]
Hey,

sure. I'll release a new version within the next few days after taking a closer look at #79

**Comment by toshimaru** [comment]
+1

**Comment by tobmatth** [comment]
Hey,

0.2.9 should be available via Rubygems...
