### ISSUE TITLE
Issue with IE only... strict true not working

### ISSUE THREAD

**Issue by jgrannas** [tobmatth/rack-ssl-enforcer#80]
On rails4.2.1 and the latest rack-ssl-enforcer.

This my setup, in application.rb
```
    config.middleware.use Rack::SslEnforcer, :only_environments => ['production','staging'], :only => [ %r{^/admin}, %r{^/account}, %r{^/checkout}, %r{^/ckeditor} ], :except => ["/account/sign_out"], :strict => true
```

When i use chrome, and visit mydomain.com/account/sign_in it forwards to HTTPS https://mydomain.com/account/sign_in properly. 

However, when i visit that same URL in ie11 (version 11.0.9600.17728), it stays HTTP. I have a devise ajax login on this page, so it then tries to post to HTTP which causes issues. Whats really odd, and frustrating is that seems isolated to specific IE version

IE9: works
IE10: works
IE11: version 11.0.9600.17728 DOES NOT WORK
IE11: version 11.0.9600.17420 works!

Am I doing something wrong here or is this a bug

**Comment by tobmatth** [comment]
Hmm,

any idea how i can get my hands on that specific IE version?

**Comment by PhilTee** [comment]
@tobmatth @jgrannas I believe that IE 11.0.9600.17728 is provided by KB3038314, which is recognized as having a number of issues (https://support.microsoft.com/en-us/kb/3038314)

**Comment by tobmatth** [comment]
Thanks for the update. I'm closing here...
