### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Antonio-usa2015** [tobmatth/rack-ssl-enforcer#85]
After following the instructions adding:
in gemfile: gem 'rack-ssl-enforcer'  (and run bundle install)
in sinatra.rb
require 'rack/ssl-enforcer'
use Rack::SslEnforcer
set :session_secret, 'asdfa2342923422f1adc05c837fa234230e3594b93824b00e930ab0fb94b'

#Enable sinatra sessions
use Rack::Session::Cookie, :key => '_rack_session',
    :path => '/',
    :expire_after => 2592000, # In seconds
    :secret => :session_secret

When starting (by default in port 4567), always connection refused.
I tried adding the :http_port => 4567 but same result.

**Comment by tobmatth** [comment]
I am not familiar with Sinatra, but are you sure there is a SSL enabled server listening on Port 443?

**Comment by tobmatth** [comment]
I'm closing here due to inactivity. Feel free to reopen...
