### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by joelpresence** [tobmatth/rack-ssl-enforcer#95]
A changelog would help when reviewing releases.  For example looking at 0.2.8 to 0.2.9, a changelog would make the changes more clear than a git diff.

Thanks!  :-)

**Comment by joelpresence** [comment]
For reference, here's the diff: https://github.com/tobmatth/rack-ssl-enforcer/compare/e1f3dc7...66b5291

**Comment by tobmatth** [comment]
Here you go: https://github.com/tobmatth/rack-ssl-enforcer/blob/master/CHANGELOG.md
